name: Test workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch para executar o workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Exibir nome da Branch escolhida
      run: |
        echo "A Branch selecionada foi: ${{ github.event.inputs.branch }}"
